<?php
return [
    // Authentication routes
    'GET /' => 'HomeController@index',
    'GET /home' => 'HomeController@index',
    'GET /dashboard' => 'Auth/DashboardController@index',

    // Auth routes
    'GET /login' => 'Auth/AdminLoginController@show',
    'POST /login' => 'Auth/AdminLoginController@login',
    'GET /logout' => 'Auth/AdminLoginController@logout',
    'POST /logout' => 'Auth/AdminLoginController@logout',
    'GET /admin/login' => 'Auth/AdminLoginController@show',
    'POST /admin/login' => 'Auth/AdminLoginController@login',
    'POST /admin/logout' => 'Auth/AdminLoginController@logout',
    
    // Change Password routes
    'GET /change-password' => 'Auth/ChangePasswordController@show',
    'POST /change-password' => 'Auth/ChangePasswordController@update',
    
    // Forgot Password routes
    'GET /forgot-password' => 'Auth/ForgotPasswordController@show',
    'POST /forgot-password' => 'Auth/ForgotPasswordController@sendOTP',
    'GET /verify-otp' => 'Auth/ForgotPasswordController@showVerifyOTP',
    'POST /verify-otp' => 'Auth/ForgotPasswordController@verifyOTP',
    'GET /reset-password' => 'Auth/ForgotPasswordController@showResetPassword',
    'POST /reset-password' => 'Auth/ForgotPasswordController@resetPassword',

    // Admin Setup routes - Display pages
    'GET /admin/roles' => 'AdminSetupController@roles',
    'POST /admin/roles/store' => 'AdminSetupController@storeRole',
    'PUT /admin/roles/update/:id' => 'AdminSetupController@updateRole',
    'DELETE /admin/roles/destroy/:id' => 'AdminSetupController@destroyRole',
    
    'GET /admin/services' => 'AdminSetupController@services',
    'POST /admin/services/create' => 'AdminSetupController@createService',
    'POST /admin/services/update/:id' => 'AdminSetupController@updateService',
    'POST /admin/services/delete/:id' => 'AdminSetupController@deleteService',
    
    'GET /admin/item-services' => 'AdminSetupController@itemServices',
    'POST /admin/item-services/store' => 'AdminSetupController@storeItemService',
    'PUT /admin/item-services/:id' => 'AdminSetupController@updateItemService',
    'DELETE /admin/item-services/:id' => 'AdminSetupController@deleteItemService',
    
    'GET /admin/inspection-status' => 'AdminSetupController@inspectionStatus',
    'POST /admin/inspection-status/store' => 'AdminSetupController@storeInspectionStatus',
    'PUT /admin/inspection-status/:id' => 'AdminSetupController@updateInspectionStatus',
    'DELETE /admin/inspection-status/:id' => 'AdminSetupController@deleteInspectionStatus',
    
    'GET /admin/investments' => 'AdminSetupController@investments',
    'POST /admin/investments' => 'AdminSetupController@storeInvestment',
    'PUT /admin/investments/:id' => 'AdminSetupController@updateInvestment',
    'DELETE /admin/investments/:id' => 'AdminSetupController@deleteInvestment',
    
    'GET /admin/bid-types' => 'AdminSetupController@bidTypes',
    'POST /admin/bid-types' => 'AdminSetupController@storeBidType',
    'PUT /admin/bid-types/:id' => 'AdminSetupController@updateBidType',
    'DELETE /admin/bid-types/:id' => 'AdminSetupController@deleteBidType',

    // Setup routes
    'GET /setup/countries' => 'SetupController@countries',
    'POST /setup/countries' => 'SetupController@storeCountry',
    'PUT /setup/countries/:id' => 'SetupController@updateCountry',
    'POST /setup/countries/:id' => 'SetupController@updateCountry',
    'DELETE /setup/countries/:id' => 'SetupController@destroyCountry',
    'GET /setup/states' => 'SetupController@states',
    'GET /api/states/country/:countryid' => 'SetupController@getStatesByCountry',
    'POST /setup/states' => 'SetupController@storeState',
    'PUT /setup/states/:id' => 'SetupController@updateState',
    'POST /setup/states/:id' => 'SetupController@updateState',
    'DELETE /setup/states/:id' => 'SetupController@destroyState',
    'GET /setup/sublocations' => 'SetupController@sublocations',
    'POST /setup/sublocations' => 'SetupController@storeSublocation',
    'PUT /setup/sublocations/:id' => 'SetupController@updateSublocation',
    'POST /setup/sublocations/:id' => 'SetupController@updateSublocation',
    'DELETE /setup/sublocations/:id' => 'SetupController@destroySublocation',
    'GET /setup/currency' => 'SetupController@currency',
    'POST /setup/currency' => 'SetupController@storeCurrency',
    'PUT /setup/currency/:id' => 'SetupController@updateCurrency',
    'POST /setup/currency/:id' => 'SetupController@updateCurrency',
    'DELETE /setup/currency/:id' => 'SetupController@destroyCurrency',
    'GET /setup/item-types' => 'SetupController@itemTypes',
    'POST /setup/item-types' => 'SetupController@storeItemType',
    'PUT /setup/item-types/:id' => 'SetupController@updateItemType',
    'POST /setup/item-types/:id' => 'SetupController@updateItemType',
    'DELETE /setup/item-types/:id' => 'SetupController@destroyItemType',
    // Item service types (under Item Types page)
    'POST /setup/item-service-types' => 'SetupController@storeItemServiceType',
    'PUT /setup/item-service-types/:id' => 'SetupController@updateItemServiceType',
    'POST /setup/item-service-types/:id' => 'SetupController@updateItemServiceType',
    'DELETE /setup/item-service-types/:id' => 'SetupController@destroyItemServiceType',
    // Item profile options (under Item Types page)
    'GET /api/item-profile-options/:id' => 'SetupController@getItemProfileOption',
    'POST /setup/item-profile-options' => 'SetupController@storeItemProfileOption',
    'PUT /setup/item-profile-options/:id' => 'SetupController@updateItemProfileOption',
    'POST /setup/item-profile-options/:id' => 'SetupController@updateItemProfileOption',
    'DELETE /setup/item-profile-options/:id' => 'SetupController@destroyItemProfileOption',
    'GET /setup/item-doc-types' => 'SetupController@itemDocTypes',
    'POST /setup/item-doc-types' => 'SetupController@storeItemDocType',
    'PUT /setup/item-doc-types/:id' => 'SetupController@updateItemDocType',
    'POST /setup/item-doc-types/:id' => 'SetupController@updateItemDocType',
    'DELETE /setup/item-doc-types/:id' => 'SetupController@destroyItemDocType',
    'GET /setup/item-pic-types' => 'SetupController@itemPicTypes',
    'POST /setup/item-pic-types' => 'SetupController@storeItemPicType',
    'PUT /setup/item-pic-types/:id' => 'SetupController@updateItemPicType',
    'POST /setup/item-pic-types/:id' => 'SetupController@updateItemPicType',
    'DELETE /setup/item-pic-types/:id' => 'SetupController@destroyItemPicType',
    'GET /setup/inspect-pic-types' => 'SetupController@inspectPicTypes',
    'POST /setup/inspect-pic-types' => 'SetupController@storeInspectPicType',
    'PUT /setup/inspect-pic-types/:id' => 'SetupController@updateInspectPicType',
    'POST /setup/inspect-pic-types/:id' => 'SetupController@updateInspectPicType',
    'DELETE /setup/inspect-pic-types/:id' => 'SetupController@destroyInspectPicType',
    'GET /setup/payment-terms' => 'SetupController@paymentTerms',
    'POST /setup/payment-terms' => 'SetupController@storePaymentTerm',
    'PUT /setup/payment-terms/:id' => 'SetupController@updatePaymentTerm',
    'POST /setup/payment-terms/:id' => 'SetupController@updatePaymentTerm',
    'DELETE /setup/payment-terms/:id' => 'SetupController@destroyPaymentTerm',
    'GET /setup/inspection-doc-types' => 'SetupController@inspectionDocTypes',
    'POST /setup/inspection-doc-types' => 'SetupController@storeInspectionDocType',
    'PUT /setup/inspection-doc-types/:id' => 'SetupController@updateInspectionDocType',
    'POST /setup/inspection-doc-types/:id' => 'SetupController@updateInspectionDocType',
    'DELETE /setup/inspection-doc-types/:id' => 'SetupController@destroyInspectionDocType',
    'GET /setup/ownership-types' => 'SetupController@ownershipTypes',
    'POST /setup/ownership-types' => 'SetupController@storeOwnershipType',
    'PUT /setup/ownership-types/:id' => 'SetupController@updateOwnershipType',
    'POST /setup/ownership-types/:id' => 'SetupController@updateOwnershipType',
    'DELETE /setup/ownership-types/:id' => 'SetupController@destroyOwnershipType',
    'GET /setup/project-types' => 'SetupController@projectTypes',
    'POST /setup/project-types' => 'SetupController@storeProjectType',
    'PUT /setup/project-types/:id' => 'SetupController@updateProjectType',
    'POST /setup/project-types/:id' => 'SetupController@updateProjectType',
    'DELETE /setup/project-types/:id' => 'SetupController@destroyProjectType',
    'GET /setup/list-types' => 'SetupController@listTypes',
    'POST /setup/list-types' => 'SetupController@storeListType',
    'PUT /setup/list-types/:id' => 'SetupController@updateListType',
    'POST /setup/list-types/:id' => 'SetupController@updateListType',
    'DELETE /setup/list-types/:id' => 'SetupController@destroyListType',
    'GET /setup/investor-setup' => 'SetupController@investorSetup',
    'POST /setup/investor-setup' => 'SetupController@storeInvestOption',
    'PUT /setup/investor-setup/:id' => 'SetupController@updateInvestOption',
    'POST /setup/investor-setup/:id' => 'SetupController@updateInvestOption',
    'DELETE /setup/investor-setup/:id' => 'SetupController@destroyInvestOption',

    // Inspection routes
    'GET /inspection/tasks' => 'InspectionController@tasks',
    'POST /inspection/tasks/store' => 'InspectionController@storeInspectionTask',
    'PUT /inspection/tasks/:id' => 'InspectionController@updateInspectionTask',
    'GET /inspection/tasks/:id' => 'InspectionController@showInspectionTask',
    'DELETE /inspection/tasks/:id' => 'InspectionController@destroyInspectionTask',
    
    'GET /inspection/tasks/:id/team' => 'InspectionController@getInspectionTaskTeam',
    // Alias to support JS path /inspection/tasks/team/:id
    'GET /inspection/tasks/team/:id' => 'InspectionController@getInspectionTaskTeam',
    'POST /inspection/tasks/team/store' => 'InspectionController@storeInspectionTaskTeam',
    'PUT /inspection/tasks/team/:id' => 'InspectionController@updateInspectionTaskTeam',
    'DELETE /inspection/tasks/team/:id' => 'InspectionController@destroyInspectionTaskTeam',
    
    'POST /inspection/tasks/assign' => 'InspectionController@assignInspectionTask',
    
    'GET /inspection/requests' => 'InspectionController@requests',
    'POST /inspection/requests/store' => 'InspectionController@storeInspectionRequest',
    'GET /inspection/requests/:id' => 'InspectionController@showInspectionRequest',
    'PUT /inspection/requests/:id' => 'InspectionController@updateInspectionRequest',
    'DELETE /inspection/requests/:id' => 'InspectionController@destroyInspectionRequest',

    // Operations routes
    'GET /offers/active-property' => 'OffersController@activeProperty',
    'GET /offers/closed-property' => 'OffersController@closedProperty',
    'GET /offers/active-project' => 'OffersController@activeProject',
    'GET /offers/closed-project' => 'OffersController@closedProject',
    'GET /offers/property-detail/:id' => 'OffersController@propertyDetail',

    'GET /listings/dashboard' => 'ListingsController@dashboard',
    'GET /listings/new-properties' => 'ListingsController@newProperties',
    'POST /listings/add-property' => 'ListingsController@addProperty',
    'GET /listings/add-property' => 'ListingsController@addPropertyPage',
    'GET /listings/property-detail/:id' => 'ListingsController@propertyDetail',
    'GET /listings/edit-property/:id' => 'ListingsController@editPropertyPage',
    'POST /listings/edit-property/:id' => 'ListingsController@updateProperty',
    'DELETE /listings/properties/:id' => 'ListingsController@deleteProperty',
    'POST /listings/properties/reject/:id' => 'ListingsController@rejectProperty',
    'POST /listings/properties/approve/:id' => 'ListingsController@approveProperty',
    'POST /listings/properties/reinspect/:id' => 'ListingsController@reinspectProperty',
    'POST /listings/properties/list-property/:id' => 'ListingsController@listProperty',
    'POST /listings/properties/keep-for-listing/:id' => 'ListingsController@keepForListing',
    'POST /listings/properties/close-offer/:id' => 'ListingsController@closeOffer',
    'POST /listings/properties/delist/:id' => 'ListingsController@delistProperty',
    // Item extras save endpoints
    'POST /listings/properties/profiles' => 'ListingsController@saveItemProfiles',
    'POST /listings/properties/docs' => 'ListingsController@saveItemDocs',
    'POST /listings/properties/pics' => 'ListingsController@saveItemPics',
    'POST /listings/properties/layout' => 'ListingsController@savePropertyLayout',
    'GET /listings/awaiting-inspection' => 'ListingsController@awaitingInspection',
    'GET /listings/inspection-progress' => 'ListingsController@inspectionProgress',
    'GET /listings/inspection-concluded' => 'ListingsController@inspectionConcluded',
    'GET /listings/inspection-rejected' => 'ListingsController@inspectionRejected',
    'GET /listings/inspection-approved' => 'ListingsController@inspectionApproved',
    'GET /listings/awaiting-listing' => 'ListingsController@awaitingListing',
    'GET /listings/listed' => 'ListingsController@listed',
    'GET /listings/closed' => 'ListingsController@closed',

    // Investment routes
    'GET /investments/dashboard' => 'InvestmentsController@dashboard',
    'GET /investments/new-projects' => 'InvestmentsController@newProjects',
    'GET /investments/awaiting-inspection' => 'InvestmentsController@awaitingInspection',
    'GET /investments/inspection-progress' => 'InvestmentsController@inspectionProgress',
    'GET /investments/inspection-concluded' => 'InvestmentsController@inspectionConcluded',
    'GET /investments/inspection-rejected' => 'InvestmentsController@inspectionRejected',
    'GET /investments/inspection-approved' => 'InvestmentsController@inspectionApproved',
    'GET /investments/awaiting-listing' => 'InvestmentsController@awaitingListing',
    'GET /investments/listed' => 'InvestmentsController@listed',
    'GET /investments/closed' => 'InvestmentsController@closed',
    'GET /investments/add-project' => 'InvestmentsController@addProject',
    'GET /investments/edit-project' => 'InvestmentsController@editProject',
    'GET /investments/view-project' => 'InvestmentsController@viewProject',
    'POST /investments/projects/store' => 'InvestmentsController@storeProject',
    'POST /investments/projects/update-info' => 'InvestmentsController@updateProjectInfo',
    'POST /investments/projects/update/:id' => 'InvestmentsController@updateProject',
    'PUT /investments/projects/:id' => 'InvestmentsController@updateProject',
    'DELETE /investments/projects/:id' => 'InvestmentsController@destroyProject',
    'POST /investments/projects/delete/:id' => 'InvestmentsController@deleteAwaitingProject',
    'POST /investments/projects/reject/:id' => 'InvestmentsController@rejectProject',
    'POST /investments/projects/inspection-status/:id' => 'InvestmentsController@updateInspectionStatus',
    // Item extras save endpoints for investments
    'POST /investments/projects/profiles' => 'InvestmentsController@saveItemProfiles',
    'POST /investments/projects/docs' => 'InvestmentsController@saveItemDocs',
    'POST /investments/projects/pics' => 'InvestmentsController@saveItemPics',
    'POST /investments/projects/layout' => 'InvestmentsController@saveProjectLayout',
    
    // Document CRUD endpoints
    'POST /investments/projects/documents/store' => 'InvestmentsController@storeDocument',
    'GET /investments/projects/documents/:id' => 'InvestmentsController@getDocument',
    'POST /investments/projects/documents/:id/update' => 'InvestmentsController@updateDocument',
    'POST /investments/projects/documents/:id/delete' => 'InvestmentsController@deleteDocument',
    'GET /investments/projects/:id/documents' => 'InvestmentsController@getProjectDocuments',
    
    // Image CRUD endpoints
    'POST /investments/projects/images/store' => 'InvestmentsController@storeImage',
    'GET /investments/projects/images/:id' => 'InvestmentsController@getImage',
    'POST /investments/projects/images/:id/update' => 'InvestmentsController@updateImage',
    'POST /investments/projects/images/:id/delete' => 'InvestmentsController@deleteImage',
    'GET /investments/projects/:id/images' => 'InvestmentsController@getProjectImages',
    
    // Inspection and Investors endpoints
    'GET /investments/projects/:id/inspections' => 'InvestmentsController@getProjectInspections',
    'GET /investments/projects/:id/investors' => 'InvestmentsController@getProjectInvestors',
    
    // Fetch profile options for a project (by itemtypeid or itemid)
    'GET /investments/profile-options' => 'InvestmentsController@getProfileOptions',

    // Requests routes
    'GET /requests/properties' => 'RequestController@properties',
    'GET /requests/properties/:id' => 'RequestController@properties',
    'GET /requests/investments' => 'RequestController@investments',
    'GET /requests/investments/:id' => 'RequestController@investments',
    'GET /requests/properties/:id' => 'RequestController@properties',
    'GET /requests/investments/:id' => 'RequestController@investments',

    // Users routes
    'GET /users/customers' => 'UsersController@customers',
    'GET /users/attorneys' => 'UsersController@attorneys',
    'GET /users/inspectors' => 'UsersController@inspectors',
    'GET /users/admin' => 'UsersController@admin',
    'GET /users/create' => 'UsersController@create',
    'GET /users/edit' => 'UsersController@edit',
    'POST /users/store' => 'UsersController@store',
    'POST /users/update/:id' => 'UsersController@update',
    'POST /users/quick-update/:id' => 'UsersController@updateUser',
];
